name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      NETTE: nette-2.1

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup PHP 5.6
      uses: shivammathur/setup-php@v2
      with:
        php-version: '5.6'
        coverage: none

    - name: Prepare composer configuration
      run: php tests/prepare-composer.php

    - name: Install dependencies
      run: composer install --no-interaction --prefer-source --dev

    - name: Run parallel-lint
      run: ./vendor/bin/parallel-lint -e php,phpt --exclude vendor .

    - name: Tester environment
      run: ./vendor/bin/tester -c ./tests/php.ini-unix -d extension=tokenizer.so ./tests/KdybyTests/ --info

    - name: Run tests
      run: ./vendor/bin/tester -c ./tests/php.ini-unix -d extension=tokenizer.so ./tests/KdybyTests/

    - name: Display test failures
      if: failure()
      run: for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
