name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        nette-version: ['2.1.*', '2.2.*', '2.3.*', '2.4.*']
        php-version: ['5.6']

    name: PHP ${{ matrix.php-version }} / Nette ${{ matrix.nette-version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: none

    - name: Install Nette ${{ matrix.nette-version }}
      run: composer require nette/nette:${{ matrix.nette-version }} --no-update --dev

    - name: Install dependencies
      run: composer install --no-interaction --prefer-source

    - name: Run parallel-lint
      run: ./vendor/bin/parallel-lint -e php,phpt --exclude vendor .

    - name: Tester environment
      run: ./vendor/bin/tester -c ./tests/php.ini-unix -d extension=tokenizer.so ./tests/KdybyTests/ --info

    - name: Run tests
      run: ./vendor/bin/tester -c ./tests/php.ini-unix -d extension=tokenizer.so ./tests/KdybyTests/

    - name: Display test failures
      if: failure()
      run: for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
